apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: wjaa8isc5-go 
  janus-idp.io/tekton: wjaa8isc5-go
  backstage.io/kubernetes-id: wjaa8isc5-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: wjaa8isc5-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml